# Generated by Django 6.0.4 on 2026-04-17 22:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome'], 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AddField(
            model_name='funcionario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Data e hora de criação do registro', verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Marcado como deletado (soft delete)', verbose_name='Deletado?'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salário do funcionário', max_digits=10, null=True, verbose_name='Salário'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(help_text='Cargo do funcionário', max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(help_text='Email único do funcionário', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(help_text='Nome completo do funcionário', max_length=100, verbose_name='Nome completo'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro', verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de Atualização')),
                ('is_deleted', models.BooleanField(default=False, help_text='Marcado como deletado (soft delete)', verbose_name='Deletado?')),
                ('numero_pedido', models.CharField(help_text='Identificador único do pedido', max_length=20, unique=True, verbose_name='Número do Pedido')),
                ('data_pedido', models.DateField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='pending', help_text='Status atual do pedido', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Prioridade')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do pedido', verbose_name='Descrição')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='funcionarios.funcionario', verbose_name='Funcionário Responsável')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-data_pedido'],
                'indexes': [models.Index(fields=['numero_pedido'], name='funcionario_numero__bad6bb_idx'), models.Index(fields=['status'], name='funcionario_status_bdca6a_idx'), models.Index(fields=['-data_pedido'], name='funcionario_data_pe_c56d30_idx')],
            },
        ),
    ]
