# Generated by Django 6.0.4 on 2026-04-17 22:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_funcionario_options_funcionario_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data e hora de criação do registro', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora da última atualização', verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Data e hora de criação do registro', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora da última atualização', verbose_name='Data de Atualização'),
        ),
    ]
